version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    command: "npm start"
    depends_on:
      - strapi
    networks:
      - strapi

  strapi:
    build: "./linkler-cms"
    env_file: ./linkler-cms/.env
    volumes:
      - ./linkler-cms/config:/opt/app/config
      - ./linkler-cms/src:/opt/app/src
      - ./linkler-cms/package.json:/opt/package.json
      - ./linkler-cms/.env:/opt/app/.env
      - ./linkler-cms/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge