version: "3.9"

services:
  frontend:
    build: ./linkler-frontend
    container_name: linkler-frontend
    env_file: .env
    volumes:
      - ./linkler-frontend/dist:/linkler-frontend/dist
      - ./linkler-frontend/src:/linkler-frontend/src
      - ./linkler-frontend/package.json:/linkler-frontend/package.json
      - ./linkler-frontend/tasks:/linkler-frontend/tasks
      - ./linkler-frontend/index.js:/linkler-frontend/index.js
      - /linkler-frontend/node_modules
      - ./.env:/linkler-frontend/.env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - strapi
    networks:
      - strapi

  strapi:
    build: "./linkler-cms"
    container_name: linkler-cms
    env_file: .env
    volumes:
      - ./linkler-cms/config:/opt/app/config
      - ./linkler-cms/src:/opt/app/src
      - ./linkler-cms/package.json:/opt/package.json
      - ./.env:/opt/app/.env
      - ./linkler-cms/public/uploads:/opt/app/public/uploads
    ports:
      - "${PORT}:${PORT}"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
