version: "3.9"

services:
  frontend:
    build: ./linkler-frontend
    container_name: linkler-frontend
    env_file: .env
    environment:
      WEB_PORT: ${WEB_PORT}
      GTM_KEY: ${GTM_KEY}
      GA_KEY: ${GA_KEY}
    volumes:
      - ./linkler-frontend:/linkler-frontend
      - /linkler-frontend/node_modules
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - strapi
    networks:
      - strapi

  strapi:
    build: "./linkler-cms"
    container_name: linkler-cms
    env_file: .env
    volumes:
      - ./linkler-cms/config:/opt/app/config
      - ./linkler-cms/src:/opt/app/src
      - ./linkler-cms/package.json:/opt/package.json
      - ./backups:/opt/app/backups
    ports:
      - "${PORT}:${PORT}"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
