version: "3.9"

services:
  frontend:
    build:
      context: ./linkler-frontend
      dockerfile: Dockerfile
      args:
        WEB_PORT: ${WEB_PORT}
        GTM_KEY: ${GTM_KEY}
        GA_KEY: ${GA_KEY}
    container_name: linkler-frontend
    env_file: .env

    volumes:
      - ./linkler-frontend:/linkler-frontend
      - /linkler-frontend/dist
      - /linkler-frontend/node_modules
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - strapi
    networks:
      strapi:
        ipv4_address: 172.21.0.3

  strapi:
    build: "./linkler-cms"
    container_name: linkler-cms
    env_file: .env
    volumes:
      - ./linkler-cms/config:/opt/app/config
      - ./linkler-cms/src:/opt/app/src
      - ./linkler-cms/package.json:/opt/package.json
      - ./backups:/opt/app/backups
    ports:
      - "${PORT}:${PORT}"
    networks:
      strapi:
        ipv4_address: 172.21.0.2

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/29
